### ISSUE TITLE
Suggestion for improvements to index

### ISSUE THREAD

**Issue by danielgormly** [drone/drone-plugin-index#213]
I wrote a Drone Kubernetes plugin because I assumed an up-to-date one didn't exit. I pushed mine and now it just sits there as a PR. Looking at the PRs now I can see there is one but it was rejected because the documentation was not in the correct format. The current Kubernetes plugin is obviously stale - Vallard's K8s plugin even made it into recent Drone's website refresh. The curation pipeline seems very flawed considering all this. I would rather the opportunity to search through a more open central directory where I can judge the quality of the plugin myself.

Here are some suggestions to fix this problem:

1. If you want to retain some level of centralised curation, divide your categories into:
a. Core plugins maintained by Drone
b. Community plugins and optionally
c. "Recommended" community plugins

2. Remove the onus on the user of providing a clone of their documentation to this repo, and the onus on Drone to scour through all the extra detail or leave stale documentation around. It's clear Drone cannot manage it and the user shouldn't have to make a pull request every time they slightly change a plugin and manage multiple sources of truth. Tags, name, author, Github repo link, Docker registry page, one paragraph description should be about all is needed.

I'm happy to help implement something here.

**Comment by tboerger** [comment]
1) At least you can currently see where this plugin comes from, obviously drone-plugins are maintained by core contributors of Drone. Maybe it could make sense to highlight some recommended plugins.

2) The plugin index has been done in a centralized way on purpose, as we have seen that the structure and also the quality of the docs vary a lot. That's why we have decided to use this centralized approach. There are times where PRs aren't reviewed really fast, feel free to help out here. Nearly everybody of us is doing that as a volunteer. There had already been the idea to build some GitHub app/bot at https://github.com/drone/drone-plugin-index/issues/109.

Even without the merged pull requests you can already see multiple Kubernetes related plugins at http://plugins.drone.io/ like http://plugins.drone.io/vallard/drone-kube/, http://plugins.drone.io/mactynow/drone-kubernetes/ and http://plugins.drone.io/ipedrazas/drone-helm/.

**Comment by danielgormly** [comment]
Point taken, I should comment on the the PRs related to the K8s projects before complaining about the state of the index!

**Comment by tboerger** [comment]
But you are welcome to create a better plugin index. Even if the PRs are created automatically because of some kind of GitHub bot or app would improve the index a lot for sure.
